/*
 version.h

 Autogenerated by Codeblocks. Not sure who would own the copyright,
 but the copyright for this version in use by this application is retained.

 Author:
      Neil Stoker <gg6ujj@gmail.com>

 Copyright (c) 2011 Neil Stoker

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
#ifndef VERSION_H
#define VERSION_H

namespace Lib6502Version{

	//Date Version Types
	static const char DATE[] = "12";
	static const char MONTH[] = "10";
	static const char YEAR[] = "2011";
	static const char UBUNTU_VERSION_STYLE[] = "11.10";

	//Software Status
	static const char STATUS[] = "Alpha";
	static const char STATUS_SHORT[] = "a";

	//Standard Version Type
	static const long MAJOR = 0;
	static const long MINOR = 0;
	static const long BUILD = 47;
	static const long REVISION = 244;

	//Miscellaneous Version Types
	static const long BUILDS_COUNT = 57;
	#define RC_FILEVERSION 0,0,47,244
	#define RC_FILEVERSION_STRING "0, 0, 47, 244\0"
	static const char FULLVERSION_STRING[] = "0.0.47.244";

	//These values are to keep track of your versioning state, don't modify them.
	static const long BUILD_HISTORY = 47;


}
#endif //VERSION_H
